ExUnit.start()

Code.require_file("some_events.ex", "test/test_samples")
Code.require_file("process_manager_example.ex", "test/test_samples")
Code.require_file("aggregate_root_example_commands.ex", "test/test_samples")
Code.require_file("aggregate_root_example_events.ex", "test/test_samples")
Code.require_file("aggregate_root_example_errors.ex", "test/test_samples")
Code.require_file("mem_store_example.ex", "test/test_samples")
Code.require_file("command_router_example.ex", "test/test_samples")
Code.require_file("aggregate_root_example.ex", "test/test_samples")
