# This file is a template, and might need editing before it works on your project.
# This template uses the non default language docker image
# The image already has Hex installed. You might want to consider to use `elixir:latest`
image: elixir:1.3

before_script:
  - mix local.hex --force
  - mix deps.get

stages:
  - build
  - test

build:
  stage: build
  script:
  - mix compile

test:
  stage: test
  script:
  - mix test

coverage:
  stage: test
  script:
  - mix coveralls
