# This file is a template, and might need editing before it works on your project.
# This template uses the non default language docker image
# The image already has Hex installed. You might want to consider to use `elixir:latest`
image: elixir:1.3

before_script:
  - mix local.hex --force
  - mix deps.get

stages:
  - build
  - test

cache:
  key: "${CI_BUILD_REF_NAME}"
  paths:
    - "_build"
    - "deps"

build:
  stage: build
  script:
    - mix compile
  artifacts:
    expire_in: 3 day
    paths:
      - "_build"
      - "deps"

test:
  stage: test
  dependencies:
    - build
  script:
  - mix test

coverage:
  stage: test
  dependencies:
    - build
  script:
  - mix coveralls
